data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"

# model:
#   max_features: 1000
#   random_state: 42

training:
  test_size: 0.2
  batch_size: 32

text_cleaner:
  remove_stopwords: true
  lemmatize: true

tokenizer:
  num_words: 20000
  oov_token: '<OOV>'
  max_length: 128
  padding: 'post'
  truncating: 'post'

model:
  embedding_dim: 100
  lstm_units: 128
  dropout_rate: 0.5
  dense_units: 64
  output_units: 3
  activation: 'softmax'