name: Deploy Sentiment Analysis Model

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "sentiment-analysis-LSTM-model"
  REGION: ${{ secrets.GCP_REGION }}
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  IMAGE_URI: "gcr.io/${{ secrets.GCP_PROJECT }}/${{ env.IMAGE_NAME }}:latest"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Configure Docker for Google Container Registry
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_URI .

    - name: Push Docker image to GCR
      run: |
        docker push $IMAGE_URI

    # - name: Install Terraform
    #   uses: hashicorp/setup-terraform@v2
    #   with:
    #     terraform_version: 1.5.6

    # - name: Terraform Init
    #   working-directory: ./terraform
    #   run: terraform init

    # - name: Terraform Apply
    #   working-directory: ./terraform
    #   env:
    #     TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
    #     TF_VAR_region: ${{ secrets.GCP_REGION }}
    #     TF_VAR_container_image_uri: $IMAGE_URI
    #   run: |
    #     terraform apply -auto-approve